version: "3"
services:
    nexus:
      image: sonatype/nexus3
      container_name: nexus 
      restart: always
      volumes:
        - "nexus-data:/sonatype-work"
      ports:
        - "8081:8081"
        - "8085:8085" 
        - "5000:5000"
        - "8083:8083"
volumes:
  nexus-data: {}
