version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    env_file:
      - ./minio.env
    volumes:
      - /srv/minio/data:/data
    command: server /data --console-address ":9001"
    user: "${UID}:${GID}"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
    security_opt:
      - no-new-privileges:true
    read_only: true
