version: '3.8'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8080:80
    volumes:
      - /home/ftpuser/DATA:/var/www/html/data
    restart: unless-stopped
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge

